parameters:
    firebase.credentials_path: '%env(resolve:FIREBASE_CREDENTIALS_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\FcmService:
        arguments:
            $credentialsPath: '%firebase.credentials_path%'
